#!/bin/sh
printf "\n\n 
=======================================

 
Owner : @roarijo89⚜️developer⚜️
 
Owner : @stem grade⚜️developer⚜️
 
(Tools 🛠 BY ♥️roarijo89 Tweaks♥️)

            ❗️v1.4❗️

🌐Get more cools tweaks and hacks on my repo🌐
=======================================
\n\n"
